"""Minimal, append-only runtime kernel for Agent Skill task lifecycles."""

from .runtime import (
    CompletionError,
    EventEnvelope,
    EventLog,
    IntegrityError,
    InvalidTransition,
    KernelError,
    VALID_STATES,
    reduce_events,
)
from .verifiers import (
    Evidence,
    FilesystemVerifierRegistry,
    GateDecision,
    PackRegistry,
    VerifierPack,
    VerifierRunner,
    VerifierSpec,
    VerifierDefinition,
    VerifierRegistry,
    VerificationRequest,
    VerificationResult,
    apply_gate,
    builtin_verifier_root,
    normalize_result,
    snapshot_evidence,
)
from .builtins import CITATION_TRUTH_FIT_SPEC, FILE_SPEC, build_builtin_registry, collect_markdown
from .states import CombinedStateRegistry, FilesystemStateRegistry, META_STATE_PROTOCOL_VERSION, SKILL_STATE_DECLARATION_VERSION, SkillStateDeclaration, StateDefinition, StateDefinitionError, StateExecutionError, StateExecutionResult, StateTransitionError, StateMachine, build_builtin_state_registry, build_state_registry, execute_state
from .workspace import META_STATE_SNAPSHOT_VERSION, TaskWorkspace, WorkspaceError, WorkspacePaths, WORKSPACE_KINDS, WORKSPACE_PROTOCOL_VERSION, workspace_path

__all__ = [
    "CompletionError",
    "EventEnvelope",
    "EventLog",
    "IntegrityError",
    "InvalidTransition",
    "KernelError",
    "VALID_STATES",
    "reduce_events",
    "Evidence",
    "FilesystemVerifierRegistry",
    "VerifierRegistry",
    "GateDecision",
    "PackRegistry",
    "VerifierPack",
    "VerifierRunner",
    "VerifierSpec",
    "VerifierDefinition",
    "VerificationRequest",
    "VerificationResult",
    "apply_gate",
    "builtin_verifier_root",
    "normalize_result",
    "snapshot_evidence",
    "CITATION_TRUTH_FIT_SPEC",
    "FILE_SPEC",
    "build_builtin_registry",
    "collect_markdown",
    "FilesystemStateRegistry",
    "CombinedStateRegistry",
    "META_STATE_PROTOCOL_VERSION",
    "SKILL_STATE_DECLARATION_VERSION",
    "SkillStateDeclaration",
    "StateDefinition",
    "StateDefinitionError",
    "StateExecutionError",
    "StateExecutionResult",
    "StateTransitionError",
    "StateMachine",
    "build_builtin_state_registry",
    "build_state_registry",
    "execute_state",
    "TaskWorkspace",
    "WorkspaceError",
    "WorkspacePaths",
    "WORKSPACE_KINDS",
    "WORKSPACE_PROTOCOL_VERSION",
    "META_STATE_SNAPSHOT_VERSION",
    "workspace_path",
]

__version__ = "0.8.0"
